# Generated by Django 5.1 on 2025-11-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Не требуется', max_length=100, unique=True, verbose_name=''),
        ),
    ]
